### ISSUE TITLE
Don't set global &formatprg

### ISSUE THREAD

**Issue by mkoskar** [Chiel92/vim-autoformat#105]
I assume setting `formatprg` is not needed but done as a feature so one can use formatting with motions too. Either way it should be set as buffer local option.

**Edit:**
I've realized that `formatprg` is global option. Hence I suggest to not set it at all.

**Comment by Chiel92** [comment]
Shouldn't `formatprg` not being buffer local rather be fixed upstream in the vim core?  :)
I remember I did some investigation on this. E.g. have a look at https://groups.google.com/forum/?fromgroups=#!searchin/vim_dev/formatprg/vim_dev/cFK1UjstyAk/mreb2H4VCtoJ

But as it stands, setting the formatprg option is mostly an historical artifact I believe. So I would be fine with it if it were replaced with a bufferlocal variable. If you want, you could provide a Pull Request for this. Shouldn't be hard: only some minor modifications in `s:TryAllFormatters` and `s:TryFormatterPython[3]` in `autoformat.vim` as far as I know.

**Comment by mkoskar** [comment]
> If I may ask, what is the reason you'd like formatprg not to be set?

Let's start in buffer of `ft=c` do `:Autoformat`. Now `formatprg` is set according to `ft=c`, so one can use `gq` consistently. Then open different buffer of `ft=python` and trying to do `gq` it will use `formatprg` as set for `ft=c` which is inconsistent. Of course it's about how one uses it, e.g., using `:Autoformat` always is a solution. It can be handled with `BufEnter` autocommand and reset or devise some other logic, but generally probably sanest solution is to not mix `formatprg` into the picture.

**Comment by Chiel92** [comment]
Fair point. I would be okay with a pull request that changes this. As I said, it shouldn't be hard.

**Comment by sanscore** [comment]
I just hit this issue because I was doing some python coding, but now I am trying to write a git commiti message. Every time I try to fix a paragraphs formatting with `gq`, vim tries to run `autopep8` which is extremely annoying.

**Comment by Chiel92** [comment]
@sanscore Does you git commit vim instance end up in the same instance in which you do your python coding? If so, how?

**Comment by sanscore** [comment]
Yes. I use `vim-fugitive`. The exact steps that i would use in this
situation are:

* `:GStatus` to see what changes have been made and to stage them for
commit.
* Use `-` over each file to stage and unstage changes.
* Type `cvc` to open a commit tab with a diff message to help write out the
commit message.

Then I can write my commit message which will be nicely formatted thanks to
`vim-git`, except for the issue with `gq` reported here.

I'll look into doing a PR today because it does look like an easy fix.

**Comment by Chiel92** [comment]
Has been fixed by https://github.com/Chiel92/vim-autoformat/commit/4ef9e937c0ec1f5e6da95ad6df3e5343c326f9df

**Comment by kiryph** [comment]
**Update**

vim 8.0.0179 (Jan 2017) made formatprg global-local (https://github.com/vim/vim/commit/9be7c04e6cd5b0facedcb56b09a5bcfc339efe03).

I would like to use a plugin such as [vim-autoformat](https://github.com/Chiel92/vim-autoformat), [vim-codefmt](https://github.com/google/vim-codefmt) or [neoformat](https://github.com/sbdchd/neoformat) as a drop-in replacement for the builtin formatting functionality to supercharge `gq`.

I do not like to map function keys, in particular if a mapping is already present in default vim. There is no need to occupy another key on the keyboard for the same functionality. There is already `=` to re-indent which is a subset of formatting.

Any chance to provide a configuration suggestion to use vim-autoformat in such a way?

**Comment by Chiel92** [comment]
This has been suggested before: https://github.com/Chiel92/vim-autoformat/issues/80

Quoting myself:
>If I remember correctly, one of the main issues is the fact that vim does not indicate whether the formatting was a success or a failure, which makes it very hard to execute a fallback chain.
Therefore we now rely on python to manually shell out the formatter. So instead of using gq in combination with a motion you could get visual with v, do the motion and then press the format button. This is just as many keypresses. If you want to use gq, can't you map it to :Autoformat?

I did not know about the `gw` key by the way. Another reason for not overwriting `gq` was indeed to leave default behaviour intact, which by `gw` is not needed anymore.

But the technical reasons as pointed out above still stand.

**Comment by kiryph** [comment]
I understand the reason not to use `formatprg` itself. But I was hoping to actually overwrite `gq` with Autoformat taking typical settings of vim into account such as textwidth, shiftwidth, ... which affect the builtin `gq`. I think the latter part is already true.

I mean not by default, but if a user wish to do so (apparently I am not the only one).

My comment was actually misleading in the context of `formatprg` not being a global only setting anymore.

What about having following chain? `gq` invokes Autoformat and if Autoformat is not configured or fails, it falls back to vim default behavior using `formatprg`.

**Comment by Chiel92** [comment]
You probably could experiment with mappings like `noremap <expr> gq <SID>TryAllFormatters() ? <nop> : 'gq'` (untested).
If you manage to get something to work, and you think other people may benefit from it, we surely can discuss about adding it as a feature (either optional or not).
