### ISSUE TITLE
Autoformat closes gvim

### ISSUE THREAD

**Issue by michaelswanson25** [Chiel92/vim-autoformat#143]
I have cloned the repo in my plugins and when i do Autoformat, it will close gvim.

**Comment by Chiel92** [comment]
Interesting. What is you vimrc? What is the formatter you executed? How did you execute Autoformat? Can you get hold of the messages output right before it shuts down?

**Comment by michaelswanson25** [comment]
I found the vimrc line that causes the issue: set nocompatible | filetype indent plugin on | syn on

I then tried just: syntax enable

And this causes it to close too.

**Comment by Chiel92** [comment]
Weird. Does this mean you have fixed it?

**Comment by michaelswanson25** [comment]
No.  If I take out that line, AutoFormat works, but then i do not have syntax highlighting.  I can't work without syntax highlighting, so at this point i unfortunately can't use autoformat.

**Comment by Chiel92** [comment]
Still, extra information would be necessary to solve this issue, since it just works for most people WITH syntax highlighting. So:

What is you vimrc? What is the formatter you executed? How did you execute Autoformat? Can you get hold of the messages output right before it shuts down?

**Comment by slam02** [comment]
Hi,

Chipping in for future reference and maybe help you with the problem.

I had the exact same behavior with gVim on windowsn. My problem was due to python.
If entered the command ":python print 1", gvim would crash hard.

Turns out my PYTHONPATH environment variable was not set and thus making vim crash.
Once PYTHONPATH was set, I could run the python command without problem. And Autoformat started to work without problems.

Reference: http://stackoverflow.com/questions/35597157/gvim-crashes-when-running-python

Thank you.

**Comment by michaelswanson25** [comment]
AWESOME.  Autoformat is working now.  Thanks @slam02
