### ISSUE TITLE
Replacing '=' with autoformat

### ISSUE THREAD

**Issue by m-fonseca** [Chiel92/vim-autoformat#192]
Hello

I'm basically trying to replace the = command with autofilter.  Is this possible?
So that it supports motions like =% when the cursor is on a brace { , and it would format everything until the next brace.  As well as still supporting visual selections.  I want to use the '=' command because I'm very accustom to using it to indenting lines, I would just like to take it one step further and formating them as well.

I've tried setting equalprg directly to clang-format, but this has the side effect of removing the existing indention level of the first brace (probably because it looses the context of the current brace indention)

Any suggestions?

Thank you

**Comment by Chiel92** [comment]
It depends on the formatter whether vim-autoformat can do this.

https://github.com/Chiel92/vim-autoformat#ranged-definitions

Clang format supports ranges fortunately.

If you select a part of the file and execute `:Autoformat`, doesn't this behave to your liking?
Can't you map `=` to `:Autoformat` or something?

**Comment by m-fonseca** [comment]
I probably could get = mapping to :Autoformat to work (although my initial attempts remapping over a motion operator like = didn't work as expected), but it won't work as nicely then.  Just like 'dd' deletes a line, dw deletes a word, similarly,  =% formats a block of code and == formats the current line. 

It sounds like the motion support isn't there, so perhaps I can come up with a macro or function that simulates this.

Thanks

**Comment by MedicineYeh** [comment]
This is my solution written in `.vimrc`. Every auto indent trick works perfectly with these commands.

autocmd BufEnter *.c*,*.h,*.hpp exe 'vmap = :Autoformat<CR>'
autocmd BufEnter *.c*,*.h,*.hpp exe 'nmap =G :.,$Autoformat<CR>'
autocmd BufEnter *.c*,*.h,*.hpp exe 'nmap == :Autoformat<CR>'
autocmd BufEnter *.c*,*.h,*.hpp exe 'nmap =<UP> :.-1,.Autoformat<CR>'
autocmd BufEnter *.c*,*.h,*.hpp exe 'nmap =<DOWN> :.,.+1Autoformat<CR>'

**Comment by Chiel92** [comment]
@m-fonseca Does the suggestion of @MedicineYeh solve your problem?

**Comment by dzan** [comment]
@Chiel92 I had the same request and tried the solution, it doesn't work for me. I'll look into why it doesn't seem to trigger Autoformat later and report my findings.

**Comment by m-fonseca** [comment]
Better!, but still needs some tweeks.

**nmap =% :.,/}/; Autoformat<CR>** only goes to the first } .  If you have nested {} statements, it breaks. 
**nmap =% v% :Autoformat<CR>** works better, but it does cause the visual highlighting momentarily.  I'm not sure how to get a range from one brace to another without using the visual mode.  Any ideas?

**nmap == :Autoformat<CR>** by itself usually works on a single line.  This does the whole file
**:nmap == :. Autoformat<CR>** is more consistent with the original == (without supporting motions)

**Comment by MedicineYeh** [comment]
Sorry for the late reply. I was on holiday. 
I put autocmd here because I want to use default vim shortcuts for some other languages. As you mentioned, if one does not rely on vim's indention, autocmd is not needed.

As for some of the replacement.
`nmap =% :.,/}/; Autoformat ` is the only __simple__ solution I come up with without visual highlighting. You might need to write a vim function and parse the text to count the number of '{' and '}'' then find the matching '}'. Sorry that this does not fit your needs. If you find a vim function that can search for the next matching '}' with no nested braces issue, please leave it on this thread. That would solve this problem.

`nmap == :Autoformat` is designed purposely since single line usually does not contain enough information for indention. My group does not use that shortcut, and consider it as useless. We replace it for whole document indention.  This is my fault forgetting to warn the differed behavior.

**Comment by Chiel92** [comment]
> I put autocmd here because I want to use default vim shortcuts for some other languages. As you mentioned, if one does not rely on vim's indention, autocmd is not needed.

but as said before, vim-autoformat falls back to default = behaviour anyway?
