### ISSUE TITLE
Feature: exceptions for nonzero codes for specific tools?

### ISSUE THREAD

**Issue by idgserpro** [Chiel92/vim-autoformat#268]
Check https://github.com/asottile/add-trailing-comma/issues/83 for some information about this issue.

In a nutshell: some tools return 1 just to indicate something was modified (the case with `add-trailing-comma`) but `autoformat` only applies the formatting if the status code is 0. I was thinking about a variable that you can check for different status codes for different tools. The default is still 0.

**Comment by Chiel92** [comment]
Looking at the sourcecode (https://github.com/asottile/add-trailing-comma/blob/master/add_trailing_comma.py) I would say that the exitcodes used in that tool are badly designed. It is not possible to distinguish between e.g. unicode decode error and a successful run with changes being made.

Secondly, I would say that tool is conceptually not a formatter. Because for a formatter a successful run would involve formatting the code, whereas in that tool, formatting is seen as a failure (due to exitcode > 0). So it's more of a weird checker+formatter mashup. 

I'm inclined to oppose the introduction of complexity for dealing with conceptually invalid cases. However, if this problem starts to occur for more tools, then the complexity may be justified and I will change my mind.

For now, the right thing seems to me to patch that tool with a commandline option that let's it function as a either checker or a formatter. If the maintainer is unwilling to support that, you can wrap that tool in a shell script that always gives exitcode 0.

I will close this issue for now, but feel free to continue the discussion or bring up any thoughts.

**Comment by idgserpro** [comment]
For this specific tool, add-trailing-comma, a new parameter was added, `--exit-zero-even-if-changed`.
