### ISSUE TITLE
Autoformat Project

### ISSUE THREAD

**Issue by alexdunn** [Chiel92/vim-autoformat#35]
It would be very cool to be able to run a command that executes Autoformat on every file of a given type in the current project (the current directory and all subdirectories).

This would be useful for doing an auto-format on all files for the first time in a project that previously didn't have any auto-formatting or had a different auto-formatting scheme.

**Comment by Chiel92** [comment]
I think the usefulness of such a feature is fairly narrow since it is probably only used once per project.
One could easily just run the format program manually in a shell for this occasion. 
Nonetheless, I would merge in a sane pull request implementing this functionality, e.g. in a `:AutoformatAll` command.
