### ISSUE TITLE
How to specify external formatting program for compound filetypes?

### ISSUE THREAD

**Issue by sudar** [Chiel92/vim-autoformat#37]
I am using WordPress.vim addon which changes filetype for WordPress files to the compound file type `php.wordpress`.

I am trying to specify the autoformat programs for this compound filetype using the following, but it is not working

```
let g:formatprg_wordpress = "/Users/sudar/Dropbox/code/wp/phptidy/phptidy.php"
let g:formatprg_args_wordpress = "-q -c=/Users/sudar/Dropbox/code/dotfiles/vim/vim/phptidy-config.php"
```

Let me know how I should specify the autoformat program for these compound filetypes.

**Comment by Chiel92** [comment]
What filetype does vim detect for these files?
Type `:echo &ft` when you open such a file.

**Comment by sudar** [comment]
The filetype that vim uses is `php.wordpress`

**Comment by Chiel92** [comment]
I can't seem to reproduce. 
I installed wordpress.vim, created a file called `foo.php.wordpress` and opened it.
But the filetype is empty. Do I miss something?

**Comment by sudar** [comment]
WordPress.vim doesn't work based on filetypes, it works on based on the location in which the file is placed.

After you install [WordPress.vim](https://github.com/dsawardekar/wordpress.vim), you need to download and extract the latest version of WordPress somewhere in your file system. After that you need to set the path to where you extracted WordPress file by adding the following in your `~/.vimrc`

```
let g:wordpress_vim_wordpress_path="path/to/wordpress"
```

After that if you open any PHP file inside this path the file type will be automatically set to `php.wordpress`

Anyways you don't have to do all the above things to test vim-autoformat. You can simply test it out by running the following vim command

```
set ft=php.wordpress
```

I gave the example of WordPress.vim because that is what I am using, but the real question is how should I define the formatting program (and arguments) for compound filetypes (ie) there are more than one filetype defined for a file. Usually this is done by appending both filetypes using a `.`. eg: `php.wordpress`, `html.ruby` etc.

Most vim addons (like syntastic) handle composite or compound filetypes by [splitting them into simple types](https://github.com/scrooloose/syntastic/blob/master/doc/syntastic.txt#L767) and then applying all rules of the simple types.

So I need to how define external formatting programs (and arguments) in vim-autoform for composite/compound filetypes like `php.wordpress`. Thanks.

**Comment by Chiel92** [comment]
It doesn't make sense to apply multiple formatters if the filetype is composite.
In your case I suppose you just want to apply the php formatter.

Since a vim global variable can't contain dots (so `g:formatprg_php.wordpress` doesn't work) I see two options: 
- only look at the last part of the extension
- replace the dots in the filetype by underscores

I personally think the first option makes most sense, because it is very unlikely that one would want to
have a different formatter for wordpress-specific php code.

Do you have any other suggestions?
If not, I could push a patch.

**Comment by sudar** [comment]
> I personally think the first option makes most sense, because it is very unlikely that one would want to
have a different formatter for wordpress-specific php code.

Actually no. We need to use a different autoformatter for WordPress since it follows a different coding standard. Someone who is programming in PHP and WordPress would have to use a different code formatter for PHP and a different one for WordPress even though they both have the same syntax and have the same filename extension. So, the first option wouldn't work.

I think the second option is the best. (ie) replace dots with underscores.

Or an even better but slightly complex solution is to split the filetypes based on dot and then apply individual filetypes. I think this is slightly standard among different addons (or at least the one that I have used).

BTW, I solved my problem my explicitly specifying the filetype while invoking the Autoformat command. I didn't know about it when I opened this ticket.

Also thanks for an excellent addon and also for listening to my feature request.

**Comment by Chiel92** [comment]
I don't see the benefit of applying multiple formatters in a sequence by default. If wordpress code has different conventions than regular php code, you only want to apply the wordpress formatter since applying a php formatter afterwards would probably screw things up again.
Also it is not clear in which order the formatters should be applied. In contrast with utilities like error checkers, the order affects the final result. If you want to apply formatters in a sequence, you should explicitly say so. Currently you could do that by wrapping all formatters in a custom shell script, and use the shell script in `g:formatprg_<ft>`.

So I understand that you solved your problem by something like
```vim
au filetype php.wordpress noremap <F3> :Autoformat wordpress<CR><CR>
```
which is a fair solution in my opinion. But I guess that replacing dots with underscores would be even nicer.
I will look into that.

**Comment by Chiel92** [comment]
@sudar I pushed a solution. Please verify if this works for you.

**Comment by sudar** [comment]
> I don't see the benefit of applying multiple formatters in a sequence by default. If wordpress code has different conventions than regular php code, you only want to apply the wordpress formatter since applying a php formatter afterwards would probably screw things up again.

I was comparing this plugin with syntastic's behaviour, but I think I agree with you. It doesn't make sense to have two formatters for a single file. 

> So I understand that you solved your problem by something like

Yes. In fact I was just calling the command directly from vim. (I try to use as less mapping as possible :) )

> I pushed a solution. Please verify if this works for you.

Just checked it and it works perfectly. 

Once again thanks for the excellent plugin and also for spending time to implement my feature request.
