### ISSUE TITLE
Wrong indentation when using a range / support range with commands

### ISSUE THREAD

**Issue by blueyed** [Chiel92/vim-autoformat#47]
When using `gqq` on the third line of this:

    def foo():
        if True:
            pass

It will become this:

    def foo():
        if True:
        pass

That's probably caused by `autopep8` not having enough context here,
because it only sees the `pass` line by itself.

Would it be possible for vim-autoformat to pass the whole buffer, but only
update/change the region that is being given?

There's a `--line-range` option for `autopep8`, which would allow for something like:
- write buffer to a temporary file
- call `autopep8 --line-range 3 3 -d $tempfile`
- apply the diff to the current buffer

A generic approach would then have to use a special/new setting for programs that support ranges.
Does that sound sensible?

btw: I've noticed that the `:Autoformat` command doesn't support a range,
while this is possible through `gq`.

**Comment by Chiel92** [comment]
Thanks for your suggestion. This indeed sounds like a reasonable feature.

Your proposed implementation makes use of a $tempfile. Is it not possible to use the buffer directly instead?

>btw: I've noticed that the :Autoformat command doesn't support a range,
while this is possible through gq.

That is because historically vim-autoformat only set the `&formatprg` variable and used the existing `gq` functionality from vim to format the buffer. `:Autoformat` was a shortcut for applying `gq` to the entire buffer. In my opinion it's not necessary to have `:Autoformat` accept ranges as well, as this can be done through `gq`, but then again it can't hurt either.

**Comment by Chiel92** [comment]
Hi @blueyed,

I've made an attempt at solving this issue. My current implementation is on the multiple-formatters branch.
The README.md on that branch has been updated to cover the new configuration variables.
Could you please have a look, and verify if it solves your problems? In that case, this issue would be solved.

**Comment by Chiel92** [comment]
This should be fixed in the new update.
