### ISSUE TITLE
Issue with python module not loading when formatting any filetype

### ISSUE THREAD

**Issue by RatanRSur** [Chiel92/vim-autoformat#66]
Error detected while processing function <SNR>15_TryAllFormatters..<SNR>15_TryFormatterPython:
    line   26:
    E887: Sorry, this command is disabled, the Python's site module could not be loaded.

**Comment by Chiel92** [comment]
I need some more information, as I do not experience this problem myself. I assume you get this when running `:Autoformat`, is that correct? Any other details?

What is your vim version (`vim --version`)?
Is vim-autoformat up-to-date? Which OS do you run?

**Comment by RatanRSur** [comment]
Sorry about that, here are some more details
    7.4.712
    :Autoformat
    OS X Yosemite (10.10)
Autoformat should be up to date, just updated again with Vundle just to make sure.

**Comment by Chiel92** [comment]
Do you have vim with builtin python support? Which version?
What python version do you run on your OSX system?

**Comment by RatanRSur** [comment]
`Python 2.7.10`
`Python 3.4.3`
This is what shows plugin support yes?:
`+python`
`-python3`

**Comment by RatanRSur** [comment]
Sorry, accidentally closed it.

**Comment by Chiel92** [comment]
It is probably the same issue as is raised here: https://github.com/powerline/powerline/issues/1385 (please confirm).
This cannot be fixed in vim-autoformat. A possibility is to downgrade to python 2.7.9. or follow some worksarounds named in the referenced issue.

**Comment by RatanRSur** [comment]
Those workarounds don't seem to fix it for me, I'm guessing this bug lies on their end though and not yours.

**Comment by 0racle** [comment]
I have run into this same issue. Here's how I fixed in case it helps anyone.

I use pyenv to manage multiple python versions. I had build vim with python support, and then months later, installed a new release of python with pyenv. After I had migrated to the newer python, I deleted the old instance, which caused this issue.

I guess I could have reinstall the old python, but I instead chose to rebuild a newer vim with the new Python.

In any event, this is not an issue with AutoFormat.
