### ISSUE TITLE
Using `:Autoformat` sets 'formatprg' / re-add support for `gq`

### ISSUE THREAD

**Issue by blueyed** [Chiel92/vim-autoformat#80]
I've noticed that support for `gq` has been removed (dfd9461f), which was previously handled like this:

    noremap <expr> gq <SID>set_formatprg() ? 'gq' : 'gq'

Since `gq` makes use of `'formatprg'`, and invoking `:Autoformat` sets and does not restore it, `gq` appears to be (accidentally?) supported still, after you've manually called `:Autoformat` once.

Given that, what was the reason for removing direct support of `gq`, and do you think it could be re-added (to work right away)?

**Comment by Chiel92** [comment]
I don't exactly recall the reason for not supporting `gq` anymore, but is it not obsolete anyway?
If you want to use gq instead, can't you map it to `:Autoformat`?

**Comment by w0ng** [comment]
:+1:  for gq support.

`gq` is useful for text object selections.

e.g. typing: 
`gqq`, `gqi{`, `gqap`

for formatting:
a single line, between {}, and a paragraph, respectively.

The same could be accomplished with visual selections and then vmap to `:Autoformat`, but that means a few more key presses

**Comment by Chiel92** [comment]
If I remember correctly, one of the main issues is the fact that vim does not indicate whether the formatting was a success or a failure, which makes it very hard to execute a fallback chain.
Therefore we now rely on python to manually shell out the formatter.

So instead of using `gq` in combination with a motion you could get visual with `v`, do the motion and then press the format button. This is just as many keypresses.
